name: Inscription
main: net.samongi.Inscription.Inscription
version: 0.5
description: Adds levelable glyphs which augment a player
author: Migsect
website: https://github.com/Migsect/Inscription/
depend: [SamongiLib]
commands:
  inscription:
    description: This is the hub command for the plugin.
    usage: /<command>
    aliases: [inscript]