name: Inscription
main: net.samongi.Inscription.Inscription
version: 1.0
api-version: 1.13
description: Adds the ability to buff your player using glyphs
author: Migsect
depend: [SamongiLib]
commands:
  inscription:
    description: This is the hub command for the plugin.
    usage: /<command>
    aliases: [inscript]